version: 2
formats:
 - pdf
python:
  version: 3.6
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
      extra_requirements:
        - CLI
  system_packages: false

