notifications:
  email: false
sudo: required
matrix:
 include:
 - os: osx
   language: generic
   env: MAC_PYTHON_VERSION=3.6
 - os: osx
   language: generic
   env: MAC_PYTHON_VERSION=3.7
 - os: linux
   language: python
   python: 3.6
before_install:
# install other dependencies
- source ./.travis/${TRAVIS_OS_NAME}_setup_python.sh $MAC_PYTHON_VERSION
install:
# install binary packages
- travis_retry pip install --upgrade pip setuptools wheel
# install all dependencies
- travis_retry pip install git+git://github.com/AFM-analysis/afmformats.git
- travis_retry pip install -e .[CLI]
# for tests:
- travis_retry pip install codecov coverage flake8
- pip freeze
script:
- coverage run --source=nanite ./setup.py test
- coverage report -m
- flake8 tests
- flake8 afmformats
- flake8 examples
after_success:
- codecov
before_deploy:
- python setup.py sdist
- bash ./.travis/${TRAVIS_OS_NAME}_build_wheel.sh
deploy:
  provider: pypi
  user: "ci_afm"
  password:
    secure: "gi8ROhl4V+1NThdrmLaN4aJ7FRYkxiEDv+zK/cFTY1AnCXRNN/UlW3y/Rp27RXFuDS0N7cKSLlo38aPg6bsbx3IMCK39Juyo07nr3Xnv1GbMCLhrvMLqM8unOJnC5+vkWbYROsyo9uYWo6SmXvDnxk+t2zg6fk/Y5XABmYr3x9FZRqUFqAulvWEb3qcE6p2aBR43w0woFR2uyn4MwhTYMYVKWaYnUxllbmYs2iWuMqbep0eodDnxTjomkJL0B0yDE5hYeGe4o5Qp2N2GqGLT06qFeg3xJBkkS6q1tiNtSPvHbU5oaxNgQ3uqiNq+eAB+nk0WIimR/qxRLwj9luWFEKdLqTlzex5vhhjC2wkGnbt5/t3aV2QRBf+L28a3UjNglmSe8lpU6eCkiu4zICCxPhWPq8AO8sNX44sWNxBHcS4hOZDfJD9eb9kXkjYfr2P7eLcDzkXb77IbSH5iBmeDBi3vI49dl+4/zerUvxyeLpNYoTBwUPsH5f3kDqj/sn94or6K94koVqOqr4Pz9MdBCGzyhF/bvubWLFw0BlRgNeANyjQbuxt0/Jq9JHz0vNp7qH3g9O1EX46mzYELCtrObOYD75gMVssWTyYvD9L25Xf0Txw2QHtHyDhu+2w0ivpJ+IcJRWOJZ2sG0b2eILGMbkFaaymEp0NdVfHNR2ooP80="
  on:
    tags: true
  skip_cleanup: true
  skip_existing: true
