# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '3.5.4.post4+g4b11b03.d20230721'
__version_tuple__ = version_tuple = (3, 5, 4, 'g4b11b03.d20230721')
